project:
  type: website
  render: 
    - "*.qmd"
    - "!*.md"

execute:
  freeze: true

website:
  title: "Kevin Reuning"
  site-url: "https://kevinreuning.com/"
  open-graph: true
  navbar:
    left:
      - cv/index.qmd
      - teaching/index.qmd
      - research/index.qmd
      - blog/index.qmd
      - sidebar:workshops
      - resources/index.qmd
      - text: Union Elections
        href: https://unionelections.org/
    right:
      - text: Google Scholar
        href: https://scholar.google.com/citations?user=yVgvTK4AAAAJ
      - text: Bluesky
        href: https://bsky.app/profile/reuning.bsky.social
      - icon: envelope
        href: mailto:Kevin.Reuning@gmail.com
      - icon: github
        href: https://github.com/reuning/
  sidebar: 
    - id: workshops
      title: Workshops
      collapse-level: 2
      style: "docked"
      contents: 
        - section: One off
          contents: workshops/individual/*
        - section: R Bootcamp
          contents: workshops/r_bootcamp/*
        - section: SNA
          contents: workshops/sna/*
  
format:
  html:
    theme: [literia]
    toc: true
    include-in-header: 
      - text: |
          <script defer data-domain="kevinreuning.com" src="https://plausible.io/js/script.file-downloads.outbound-links.js"></script>

