project:
  type: website
  render: 
    - "*.qmd"
    - "!*.md"

website:
  title: "Kevin Reuning"
  navbar:
    left:
      - cv/index.qmd
      - teaching/index.qmd
      - sidebar:resources
      - text: Union Elections
        href: https://unionelections.org/
    right:
      - text: Google Scholar
        href: https://scholar.google.com/citations?user=yVgvTK4AAAAJ
      - text: Bluesky
        href: https://bsky.app/profile/reuning.bsky.social
      - icon: envelope
        href: mailto:Kevin.Reuning@gmail.com
      - icon: github
        href: https://github.com/reuning/
  sidebar: 
    - id: resources
      title: Resources
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        resources/*


format:
  html:
    theme: [literia]
    toc: true

