baseURL = 'http://kevinreuning.com/'
languageCode = 'en-us'
title = 'Kevin Reuning'
theme = 'soho'


summarylength = 10
enableEmoji = true

[params]
author = "Kevin Reuning"
description = "Assistant Professor of Political Science"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/profile.jpg"

copyright = "Kevin Reuning"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"
customCss = ["css/custom.css"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "#"

[menu]

  [[menu.main]]
  name = "Union Election Data"
  identifier = "union"
  weight = 400
  url = "https://unionelections.org/"

  [[menu.main]]
  name = "CV"
  identifier = "cv"
  weight = 200
  url = "/cv/"

  [[menu.main]]
  name = "Resources"
  identifier = "resources"
  weight = 300
  url = "/resources/"

[markup]
	defaultMarkdownHandler = "pandoc"
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$', '^nvim$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']