baseURL = 'https://kevinreuning.com/'
languageCode = 'en-us'
title = 'Kevin Reuning'
theme = ['soho']


summarylength = 10
enableEmoji = true

#googleAnalytics = "G-Q4HC79ZRBZ"

[params]
author = "Kevin Reuning"
description = "Assistant Professor of Political Science"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/profile.jpg"

copyright = "Kevin Reuning"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#03a2ab"
customCss = ["css/custom.css"]

## Set as many as you want.
[[params.socialIcons]]
icon = "ai ai-google-scholar"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=yVgvTK4AAAAJ&hl=en"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/reuning/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/KevinReuning"

[[params.socialIcons]]
icon = "fab fa-mastodon"
title = "Mastodon"
url = "https://home.social/@kevinreuning"

[[params.socialIcons]]
icon = "fa fa-envelope"
title = "Email"
url = "mailto:kevinreuning@gmail.com"


[menu]

  [[menu.main]]
  name = "Union Election Data"
  identifier = "union"
  weight = 400
  url = "https://unionelections.org/"

  [[menu.main]]
  name = "CV"
  identifier = "cv"
  weight = 200
  url = "/cv/"

  [[menu.main]]
  name = "Teaching"
  identifier = "teaching"
  weight = 350
  url = "/teaching/"

  [[menu.main]]
  name = "Research"
  identifier = "research"
  weight = 375
  url = "/research/"

  [[menu.main]]
  name = "Resources"
  identifier = "resources"
  weight = 300
  url = "/resources/"

  [[menu.main]]
  name = "R Bootcamp"
  identifier = "r_bootcamp"
  weight = 300
  url = "/presentations/"


[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^pandoc$', '^nvim$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

