[build]
publish = "_site"
command = "quarto render"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "netlify-plugin-checklinks"
    [plugins.inputs]
    skipPatterns = ["/presentations/", "https://cdn", ".pdf", "https://fonts.google", "dataverse.harvard.edu", "plausible.io"]