[build]
publish = "public"
command = "pandoc --template=static/header.tex content/cv/index.md  -o static/CV.pdf && hugo --gc --minify --theme soho"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "netlify-plugin-checklinks"