---
title: Research
---

# Research 
My research is motivated by a desire to understand how political actors and groups interact to make meaning and create change. This research can be divided into three sections, political parties, the measurement of complex phenomenon, and the role of social movements and protests. Below I outline how my work has developed over the past several years and where I intend to go with it in the future. Overall my research helps us to better understand how change happens within the American political system.

## Political Parties
Broadly my work on political parties is based within the Extended Party Network theory of parties, which conceives of parties as networks of related groups. I build on this paradigm by focusing on how these networks are developed and change as well as highlighting the remaining role of party organizations. For example, in a recent piece in *Party Politics* with Laura C. Bucci we argue that the labor unions positions within the party network is a function of both their own donations to party candidates and the donations made by groups opposed to them (peak business organizations). This uses data on state party networks which comes from previous solo work of mine which was published in *State Politics and Policy Quarterly*.

In another project with A. Lee Hannah and Anne Whitesell we explore how local political parties still matter to the party network. We worked with undergraduates at Miami University and Wright State University to collect data on local party presence online. This data allows us to test a theory for how local party organizations interact with groups within the party network. We argue that existing scholarship on party networks has missed the role of *narrative creators* who help make meaning and build identity within the party. We are planning on presenting this research at the American Political Science Association conference and hope to use the feedback from it to build out a larger research project collating the different types of narrative creators. This project on local parties has also led to several additional papers that highlight the role of local parties. In one paper recently published in *Political Research Quarterly* we use an audit experiment to test how local parties respond to prospective volunteers. We find that local parties are most interested in volunteers that are already part of their demographic base, for example that local Republican parties are more likely to respond to white volunteers than Black volunteers. 

In other papers (one at *Party Politics* and one at *Research and Politics*) we examine the online presence of local parties, looking at questions of what local parties are more active online and at how changes in Facebook's algorithm influenced the reach of local parties online. 

## Measurement 

I also have an interest in how political phenomenon are measured and quantified. Overall this work argues that quantitative political scientists need to pay more attention to the constructs we are studying and how those constructs are operationalized into quantitative data. Working with Christopher J. Fariss and Michael R. Kenwick I have several articles that improve on latent measurement models, a way to quantify constructs that cannot be directly observed. In an article at *Political Analysis* we developed a 'robust dynamic latent measurement model' that better estimates latent trait that moves slowly in most cases with periodic sudden changes. We have also written about how dynamic latent measurement models can be used in a variety of situations. This includes a chapter in the *SAGE Handbook of Research Methods in Political Science and International Relations* where we outline how researchers can use measurement models focusing on the complexity inherit in measuring social processes.

Along with interests in the operationalization of constructs is an interest in how the underlying constructs is perceived. I explored this with Sean McElwee where we investigated how voters define the "working-class" in the United States. The article, published in *Politics, Groups and Identities*, was motivated by concerns that the way working-class is used in elite discussions of American politics is not reflective of how most Americans view it. We found that the most common definition of working-class for Americans focused on economic precarity. Importantly we show how using a precarity operationalization of working-class opposed to the dominant educational operationalization of working-class leads to different understandings of the political preferences of the working-class. 

## Protest

Finally, I also have an interest in social movements and protest behavior more generally. Working with Lee Ann Banaszak I surveyed protesters at the 2016 Republican and Democratic national conventions. This survey was designed to test theories of political mobilization. We published work from this project in *Mobilization*. In it we argue that individual protest goals fall along three dimensions: immediate change, cultural change, and identity formation. This builds on research that tests individual level explanations for protest participation. In particular it shows that participation goals vary across individuals even within a single protest event. 

In a new project with Chris Fariss and Jay Ulfeder I combine my interest in social movements with my interest in measurement. Using data from the Crowd Counting Consortium we have built a measure of protest activity at the county level. Protest event data is naturally very messy, reports of crowd sizes are not always present and they often vary. In estimating our county level scores we take this into account to develop a measure that we argue accurately captures variation across counties and overtime. We will be presenting this work at the American Political Science Association conference and hope to submit it for review in the following months. 