---
title: Installing R and RStudio
---

In order to install RStudio you need to first install R. The instructions walk through how to do this and where to find everything.

## Mac OSX 10.11+


1. Download the most recent version of [R from here](https://cran.r-project.org/bin/macosx/). This will be in the form of R-X.Y.Z.pkg. Currently it is R-4.4.1.pkg. Note: If you have an older Mac with Intel chips you need to install the version below this with x86_86 in the filename (if you aren’t certain, ignore this and if you have trouble talk to me)
2. Once it has downloaded click on the file and follow the prompts to install it.
3. Finally download the most recent version of [RStudio from here](https://posit.co/download/rstudio-desktop/#download). Scroll to the table and there should be a row that says “macOS 12+”, click the download link to the right of that. Once it downloads again click to load the drive and then drag the RStudio icon into your applications folder.
4. Open **RStudio** to ensure that everything loads right.

Note: When you first open RStudio a window might pop-up about installing RTools or Command Line Utilities. These aren’t necessary for this course so you can ignore this.

## Windows 10 and 11

1. Download the most recent version of [R from here](https://cran.r-project.org/bin/windows/base/). This will be in the form of ‘Download R X.Y.Z for Windows’. Currently it is R-4.4.1
2. Once it has downloaded click on the file and follow the prompts to install it.
3. Download the most recent version of [RStudio from here](https://posit.co/download/rstudio-desktop/#download). TScroll to the table and there should be a row that says “Windows 10/11”, click the download link to the right of that. Once it downloads again click on it and follow the install instructions.
4. Open **RStudio** to ensure that everything loads right.
